bucket_name        = "lukas-ball-s3-example-website"
website_files_path = "website/"
r53_zone_name      = "s3_example.co.uk"
root_html_path = "index.html"
git_repo = "example-s3-bucket-website"
git_user  = "lukasb27"
git_branch = "main"